name: Main CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'

permissions:
  contents: write
  id-token: write

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make local

    - name: Test
      run: make test

    # Only try to publish the container image from the root repo; forks don't have permission to do so and will always get failures.
    - name: Publish container image
      if: github.repository == 'vmware-tanzu/velero-plugin-for-aws'
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        ./hack/docker-push.sh

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.6.0'
      with:
        workload_identity_provider: 'projects/298797809281/locations/global/workloadIdentityPools/velero-pool/providers/velero-provider'
        service_account: 'gcraccount@velero-gcp.iam.gserviceaccount.com'
        create_credentials_file: true

    - name: Set up gCloud SDK
      uses: 'google-github-actions/setup-gcloud@v0.5.0'

    - name: Configure docker for GCR
      run: |
        rm ~/.docker/config.json
        #gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        #gcloud iam service-accounts keys create keyfile.json --iam-account gcraccount@velero-gcp.iam.gserviceaccount.com
        #gcloud auth activate-service-account gcraccount@velero-gcp.iam.gserviceaccount.com --key-file=keyfile.json
        gcloud auth configure-docker gcr.io -q
        cat ~/.docker/config.json

    # Push image to GCR to facilitate some environments that have rate limitation to docker hub, e.g. vSphere.
    - name: Publish container image to GCR
      run: |
        docker pull busybox:1.35.0
        docker tag busybox:1.35.0 gcr.io/velero-gcp/busybox:1.35.0
        docker push gcr.io/velero-gcp/busybox:1.35.0
